//Generated by webfiles.py

//5 file(s) :
//  /term.html
//     size : 1160 bytes
//     content_type : text/css
//  /icons/greenArrow.png
//     size : 413 bytes
//     content_type : text/css
//  /icons/redArrow.png
//     size : 406 bytes
//     content_type : text/css
//  /scripts/term.js
//     size : 3439 bytes
//     content_type : text/css
//  /styles/term.css
//     size : 1169 bytes
//     content_type : text/css

#ifndef WiFiTerm_webfiles_h
#define WiFiTerm_webfiles_h

#if defined(ESP32)
  #include <WebServer.h>
#elif defined(ESP8266)
  #include <ESP8266WebServer.h>
  #define WebServer ESP8266WebServer
#endif

class WiFiTerm_webfiles_c
{
  public :
    WiFiTerm_webfiles_c();

    void begin(WebServer &webServer);

  private :
    WebServer *server;

    static void send_webfiles_term_html();
    static void send_webfiles_icons_greenArrow_png();
    static void send_webfiles_icons_redArrow_png();
    static void send_webfiles_scripts_term_js();
    static void send_webfiles_styles_term_css();
};

extern WiFiTerm_webfiles_c WiFiTerm_webfiles;

#endif

